#!/usr/bin/env python3
import argparse
import csv
import sqlite3
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
TRAINING_DATA = REPO_ROOT / "training_data"
ETOXPRED = REPO_ROOT / "etoxpred"
SITE = REPO_ROOT / "site"
SCRIPTS = REPO_ROOT / "scripts"


def count_compounds():
    counts = {}
    for smi_file in TRAINING_DATA.glob("*.smi"):
        with open(smi_file) as f:
            counts[smi_file.stem] = sum(1 for line in f if line.strip())
    return counts


def build_database():
    print("\n" + "=" * 60)
    print("Building SQLite Database")
    print("=" * 60)

    db_path = SITE / "chemicals.db"
    if db_path.exists():
        db_path.unlink()

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    cur.execute("""
        CREATE TABLE chemicals (
            id INTEGER PRIMARY KEY,
            smiles TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL,
            category TEXT NOT NULL,
            tox_score REAL,
            sa_score REAL,
            carc_score REAL,
            psych_score REAL,
            endo_score REAL
        )
    """)
    cur.execute("CREATE INDEX idx_category ON chemicals(category)")
    cur.execute("CREATE INDEX idx_name ON chemicals(name)")

    chemicals = {}
    category_map = {
        "nootropics": "nootropic",
        "psychoactive_drugs": "psychoactive",
        "carcinogens": "carcinogen",
        "endocrine_disruptors": "endocrine_disruptor",
    }

    for smi_file in TRAINING_DATA.glob("*.smi"):
        category = category_map.get(smi_file.stem, smi_file.stem)
        with open(smi_file) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                parts = line.split("\t")
                if len(parts) >= 2:
                    smiles, name = parts[0], parts[1]
                    if smiles not in chemicals:
                        chemicals[smiles] = {"name": name, "category": category}
                    else:
                        # Accumulate categories as comma-separated
                        existing_cats = set(chemicals[smiles]["category"].split(","))
                        existing_cats.add(category)
                        chemicals[smiles]["category"] = ",".join(sorted(existing_cats))

    # Load EtoxPred scores (Tox-score and SAscore) from results files
    tox_scores = {}
    sa_scores = {}
    
    # Read from all results_*.csv files generated by EtoxPred
    for results_file in ETOXPRED.glob("results_*.csv"):
        with open(results_file) as f:
            reader = csv.DictReader(f)
            for row in reader:
                smiles = row.get("smiles")
                if smiles:
                    try:
                        tox_scores[smiles] = float(row.get("Tox-score", 0) or 0)
                        sa_scores[smiles] = float(row.get("SAscore", 0) or 0)
                    except (ValueError, TypeError):
                        pass

    custom_scores = {}
    custom_path = ETOXPRED / "custom_scores.csv"
    if custom_path.exists():
        with open(custom_path) as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row and "smiles" in row:
                    try:
                        custom_scores[row["smiles"]] = {
                            "carcinogen": float(row.get("carcinogen_score", 0) or 0),
                            "psychoactive": float(row.get("psychoactive_score", 0) or 0),
                            "endocrine": float(row.get("endocrine_score", 0) or 0),
                        }
                    except (ValueError, KeyError):
                        pass

    for smiles, data in chemicals.items():
        tox = tox_scores.get(smiles)
        sa = sa_scores.get(smiles)
        custom = custom_scores.get(smiles, {})
        cur.execute(
            """
            INSERT INTO chemicals 
            (smiles, name, category, tox_score, sa_score, carc_score, psych_score, endo_score)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
            (
                smiles,
                data["name"],
                data["category"],
                tox,
                sa,
                custom.get("carcinogen"),
                custom.get("psychoactive"),
                custom.get("endocrine"),
            ),
        )

    conn.commit()
    total = cur.execute("SELECT COUNT(*) FROM chemicals").fetchone()[0]
    conn.close()

    print(f"  Database: {total} chemicals")
    print(f"  Written to: {db_path}")
    return total


def train_models():
    print("\n" + "=" * 60)
    print("Training Models")
    print("=" * 60)

    train_script = SCRIPTS / "train_classifiers.py"
    if not train_script.exists():
        print(f"  ERROR: {train_script} not found")
        return False

    result = subprocess.run(
        [sys.executable, str(train_script)],
        cwd=SCRIPTS,
        capture_output=False,
    )
    return result.returncode == 0


def main():
    parser = argparse.ArgumentParser(
        description="Rebuild chemical database and/or retrain classification models"
    )
    parser.add_argument(
        "--db-only",
        action="store_true",
        help="Only rebuild the database (skip model training)",
    )
    parser.add_argument(
        "--models-only",
        action="store_true",
        help="Only train models (skip database rebuild)",
    )
    args = parser.parse_args()

    print("=" * 60)
    if args.db_only:
        print("Rebuild: Database Only")
    elif args.models_only:
        print("Rebuild: Models Only")
    else:
        print("Rebuild All: Database + Models")
    print("=" * 60)

    counts = count_compounds()
    print("\nCurrent compound counts:")
    for name, count in sorted(counts.items()):
        print(f"  {name}: {count}")
    print(f"  Total: {sum(counts.values())}")

    if not args.db_only:
        if not train_models():
            print("\nERROR: Model training failed")
            sys.exit(1)

    if not args.models_only:
        total = build_database()
        print("\n" + "=" * 60)
        print("DONE")
        print("=" * 60)
        if not args.db_only:
            print(f"  Models retrained and saved to {ETOXPRED}/")
        print(f"  Database rebuilt: {total} chemicals")
        print(f"  Site database: {SITE / 'chemicals.db'}")
    else:
        print("\n" + "=" * 60)
        print("DONE")
        print("=" * 60)
        print(f"  Models retrained and saved to {ETOXPRED}/")


if __name__ == "__main__":
    main()
